import { addDays, subDays } from "date-fns";
import { formatInTimeZone } from "date-fns-tz";

import type { DashboardData } from "./types";

const now = new Date();
const date = (offset: number) => formatInTimeZone(addDays(now, offset), "America/Chicago", "yyyy-MM-dd");

export function getDemoDashboardData(): DashboardData {
  return {
    metrics: {
      dueSoon: 2,
      moneyAtRiskCents: 14306,
      pendingRefundCents: 5411,
      needsReview: 1,
    },
    mailbox: {
      connected: false,
      email: "orders@example.com",
      lastSyncAt: subDays(now, 1).toISOString(),
      status: "demo",
      error: null,
      moreAvailable: false,
      reauthorizationRequired: false,
    },
    orders: [
      {
        id: "demo-order-1",
        orderNumber: "112-0000000-0000001",
        orderedAt: subDays(now, 24).toISOString(),
        recipient: "Household",
        destination: "NORTH TEXAS, TX",
        totalCents: 15486,
        amazonUrl: "https://www.amazon.com/gp/css/order-history",
        items: [
          {
            id: "demo-item-1",
            title: "Portable rechargeable handheld fan with power bank",
            quantity: 1,
            priceCents: 1307,
            lifecycleStatus: "delivered",
            decision: "undecided",
            returnState: null,
            deliveredAt: subDays(now, 23).toISOString(),
            deadline: date(7),
            deadlineSource: "estimated",
            dropoffDeadline: null,
            promisedRefundDate: null,
            expectedRefundCents: null,
            actualRefundCents: null,
            refundMethodMasked: null,
            notes: null,
            tags: ["travel"],
            amazonUrl: "https://www.amazon.com/gp/css/order-history",
            imageUrl: null,
            archivedAt: null,
          },
          {
            id: "demo-item-2",
            title: "Personal cooling system with fan and cooling plate",
            quantity: 1,
            priceCents: 12999,
            lifecycleStatus: "delivered",
            decision: "return_planned",
            returnState: null,
            deliveredAt: subDays(now, 29).toISOString(),
            deadline: date(1),
            deadlineSource: "estimated",
            dropoffDeadline: null,
            promisedRefundDate: null,
            expectedRefundCents: null,
            actualRefundCents: null,
            refundMethodMasked: null,
            notes: "Compare cooling performance before the deadline.",
            tags: [],
            amazonUrl: "https://www.amazon.com/gp/css/order-history",
            imageUrl: null,
            archivedAt: null,
          },
        ],
      },
      {
        id: "demo-order-2",
        orderNumber: "112-0000000-0000002",
        orderedAt: subDays(now, 12).toISOString(),
        recipient: "Household",
        destination: "NORTH TEXAS, TX",
        totalCents: 5411,
        amazonUrl: "https://www.amazon.com/gp/css/order-history",
        items: [
          {
            id: "demo-item-3",
            title: "Smart home presence sensor",
            quantity: 1,
            priceCents: 5411,
            lifecycleStatus: "delivered",
            decision: "return_planned",
            returnState: "requested",
            deliveredAt: subDays(now, 10).toISOString(),
            deadline: date(20),
            deadlineSource: "estimated",
            dropoffDeadline: date(3),
            promisedRefundDate: null,
            expectedRefundCents: 5411,
            actualRefundCents: null,
            refundMethodMasked: "Visa ending in 0000",
            notes: null,
            tags: ["smart home"],
            amazonUrl: "https://www.amazon.com/gp/css/order-history",
            imageUrl: null,
            archivedAt: null,
          },
        ],
      },
      {
        id: "demo-order-3",
        orderNumber: "112-0000000-0000003",
        orderedAt: subDays(now, 3).toISOString(),
        recipient: "Family member",
        destination: "NORTH TEXAS, TX",
        totalCents: 3679,
        amazonUrl: "https://www.amazon.com/gp/css/order-history",
        items: [
          {
            id: "demo-item-4",
            title: "Insulated backpack cooler",
            quantity: 1,
            priceCents: 3399,
            lifecycleStatus: "shipped",
            decision: "undecided",
            returnState: null,
            deliveredAt: null,
            deadline: null,
            deadlineSource: null,
            dropoffDeadline: null,
            promisedRefundDate: null,
            expectedRefundCents: null,
            actualRefundCents: null,
            refundMethodMasked: null,
            notes: null,
            tags: [],
            amazonUrl: "https://www.amazon.com/gp/css/order-history",
            imageUrl: null,
            archivedAt: null,
          },
        ],
      },
    ],
  };
}
